name: OWASP ZAP Scan

on:
  push:
    paths:
      - 'index.html'

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'https://sireesha-chowdari.github.io/secure-devops-html/'

