name: OWASP ZAP Scan

on:
  push:
    paths:
      - 'index.html'

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Download ZAP
        run: |
          mkdir zap
          curl -L https://github.com/zaproxy/zaproxy/releases/download/v2.13.0/ZAP_2_13_0_unix.sh -o zap/zap.sh
          chmod +x zap/zap.sh
          ./zap/zap.sh -dir zap -quickurl https://sireesha-chowdari.github.io/secure-devops-html/ -quickout zap/report.html

      - name: Upload ZAP report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap/report.html
